/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kmp;

/**
 *
 * @author linhz
 */
public class KMPJPanel extends javax.swing.JPanel {
    private void kmpCompute() {
	String a,b;//a:for matching; b:matching key;
	a=matchingStringF.getText();
	b=matchingKeyF.getText();
	int p[]=new int[b.length()+1];
	int i,j,n=a.length(),m=b.length();
	p[1]=0;j=0;
	for (i=2;i<=m;i++){
		while(j>0 && b.charAt(j)!=b.charAt(i-1)){j=p[j];}
		if (b.charAt(j)==b.charAt(i-1)) {j++;}
		p[i]=j;
	}
	j=0;
	for (i=1;i<=n;i++){
		while(j>0 && b.charAt(j)!=a.charAt(i-1)){j=p[j];}
		if (b.charAt(j)==a.charAt(i-1)) {j++;}
		if (j==m) {
			resultTextArea.append("success matching in "+(i-m+1)+"\n");
			j=p[j];
		}
	}
    }
    /**
     * Creates new form NewJPanel
     */
    public KMPJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matchingKeyF = new javax.swing.JTextField();
        matchingStringF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();
        matchButton = new javax.swing.JButton();

        matchingStringF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchingStringFActionPerformed(evt);
            }
        });

        resultTextArea.setEditable(false);
        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane2.setViewportView(resultTextArea);

        matchButton.setText("match");
        matchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(matchingStringF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(matchingKeyF, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(matchButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchingKeyF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matchingStringF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void matchingStringFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchingStringFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matchingStringFActionPerformed

    private void matchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchButtonActionPerformed
        kmpCompute();
    }//GEN-LAST:event_matchButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton matchButton;
    private javax.swing.JTextField matchingKeyF;
    private javax.swing.JTextField matchingStringF;
    private javax.swing.JTextArea resultTextArea;
    // End of variables declaration//GEN-END:variables
}
