//red-black tree.cpp
#include <fstream>
#include <iostream>
#include <sstream>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <vector>
#include <list>
#include <algorithm>
#include <iterator>